# Generated by Django 4.2.20 on 2025-04-12 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_text', models.TextField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefiningInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('highlighted_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refining_instructions', to='refinement.highlightedsection')),
            ],
        ),
        migrations.CreateModel(
            name='RefinementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinement_sessions', to='session_manager.outputfield')),
            ],
        ),
        migrations.CreateModel(
            name='RefinedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('refined_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refining_instruction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refined_content', to='refinement.refininginstruction')),
            ],
        ),
        migrations.AddField(
            model_name='highlightedsection',
            name='refinement_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_sections', to='refinement.refinementsession'),
        ),
    ]
