# Generated by Django 5.2 on 2025-04-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndisuite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Verification Token', 'verbose_name_plural': 'Email Verification Tokens'},
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(db_index=True, editable=False, max_length=36, unique=True),
        ),
    ]
