# Generated by Django 5.2 on 2025-05-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndisuite', '0006_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google')], max_length=30),
        ),
    ]
