services:
  backend:
    volumes:
      - ./backend:/app
      - ./media:/app/media  # Ensure media directory is mounted
    environment:
      # For development mode
      - DEBUG=True
      - FRONTEND_URL=http://localhost:3000
      # Email configuration for Outlook
      - EMAIL_HOST_USER=your-outlook-email@outlook.com
      - EMAIL_HOST_PASSWORD=your-outlook-password
      - DEFAULT_FROM_EMAIL=NDISuite <your-outlook-email@outlook.com>
      # API configuration
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      # Celery configuration
      - CELERY_BROKER_URL=redis://redis:6379/0
      # MongoDB configuration
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=ndisuite
    ports:
      - "8000:8000"

  frontend:
    environment:
      # API URL - ensure it's properly configured for the frontend
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000"

  celery:
    volumes:
      - ./backend:/app
      - ./media:/app/media  # Ensure media directory is mounted
    environment:
      # Celery configuration
      - CELERY_BROKER_URL=redis://redis:6379/0
      # MongoDB configuration
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=ndisuite

  celery-beat:
    volumes:
      - ./backend:/app
      - ./media:/app/media  # Ensure media directory is mounted
    environment:
      # Celery configuration
      - CELERY_BROKER_URL=redis://redis:6379/0
      # MongoDB configuration
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=ndisuite
