# Generated by Django 4.2.20 on 2025-04-12 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=50)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.transcript')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('model', models.CharField(default='whisper-1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('input_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_job', to='session_manager.inputfile')),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='transcription.transcriptionjob'),
        ),
    ]
