apiVersion: v1
kind: Secret
metadata:
  name: ndisuite-secrets
  namespace: ndisuite-production
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  MONGODB_URI: "${MONGODB_URI}"
  # Using a placeholder for the actual API key which should be injected at deployment time
  # Requires OpenAI library v1.66.0+ and HTTPX v0.27.0+
