# Generated by Django 4.2.20 on 2025-04-12 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input_processor', '0001_initial'),
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('output_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_generations', to='session_manager.outputfield')),
            ],
        ),
        migrations.CreateModel(
            name='RAGPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_path', models.CharField(max_length=512)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=50)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_store', to='session_manager.session')),
            ],
        ),
        migrations.CreateModel(
            name='RetrievedContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField()),
                ('order', models.IntegerField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='input_processor.chunk')),
                ('rag_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_contexts', to='rag_engine.raggeneration')),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.AddField(
            model_name='raggeneration',
            name='prompt_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='rag_engine.ragprompttemplate'),
        ),
    ]
