# Generated by Django 4.2.20 on 2025-04-22 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('other', 'Other')], max_length=50)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploading', max_length=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('mongo_id', models.CharField(blank=True, max_length=50)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.session')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('source_location', models.JSONField(default=dict)),
                ('embedding_id', models.CharField(blank=True, max_length=100)),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.inputfile')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
